# Generated by Django 5.0.7 on 2024-10-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
